_wandb:
    value:
        cli_version: 0.22.1
        e:
            edl5xfi334a54hk9ltf9skt2xjm9bqk6:
                args:
                    - --resume
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "154894188544"
                        used: "38013800448"
                email: interstellarcg@gmail.com
                executable: /home/ubuntu/code/nanogpt/.venv/bin/python3
                gpu: NVIDIA A10G
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "24146608128"
                      name: NVIDIA A10G
                      uuid: GPU-d476cfac-a3ec-75f1-a526-66a0bdee4276
                host: ip-172-31-24-20
                memory:
                    total: "33263820800"
                os: Linux-6.14.0-1013-aws-x86_64-with-glibc2.39
                program: /home/ubuntu/code/nanogpt/train.py
                python: CPython 3.12.10
                root: /home/ubuntu/code/nanogpt
                startedAt: "2025-10-07T16:46:44.174694Z"
                writerId: edl5xfi334a54hk9ltf9skt2xjm9bqk6
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.12.10
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
batch_size:
    value: 512
block_size:
    value: 64
device:
    value: cuda
dropout:
    value: 0.2
learning_rate:
    value: 0.0003
max_iters:
    value: 5000
n_embd:
    value: 96
n_head:
    value: 6
n_layer:
    value: 6
